server:
  port: 8081

aggregator:
  catalog-location: classpath:/services.yml
  cache-ttl: 30s
  health-check-interval: 30s
  try-it-out-enabled: true

springdoc:
  swagger-ui:
    config-url: /swagger-config.json
    disable-swagger-default-url: true

